[package]
name = "fa-backtest"
version = "0.1.0"
edition = "2021"

[dependencies]
fa-core      = { path = "../fa-core" }
chrono       = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }

[dev-dependencies]
rust_decimal_macros = { workspace = true }
chrono              = { workspace = true }
