[package]
name = "fa-data"
version = "0.1.0"
edition = "2021"

[dependencies]
fa-core             = { path = "../fa-core" }
reqwest             = { workspace = true }
serde               = { workspace = true }
serde_json          = { workspace = true }
tokio               = { workspace = true }
async-trait         = { workspace = true }
thiserror           = { workspace = true }
chrono              = { workspace = true }
rust_decimal        = { workspace = true }
rust_decimal_macros = { workspace = true }
urlencoding         = "2"

[dev-dependencies]
mockito = { workspace = true }
tokio   = { workspace = true }
